config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users,              only: [:new, :create, :edit, :update, :index, :show]
    resources :orgs,               only: [:new, :create, :edit, :update, :index, :show]
    resources :perms,              only: [:new, :create, :edit, :update, :index, :show]
    resources :languages,          only: [:new, :create, :edit, :update, :index, :show]
    resources :templates,          only: [:new, :create, :edit, :update, :index, :show]
    resources :phases,             only: [:new, :create, :edit, :update, :index, :show]
    resources :sections,           only: [:new, :create, :edit, :update, :index, :show]
    resources :questions,          only: [:new, :create, :edit, :update, :index, :show]
    resources :question_formats,   only: [:new, :create, :edit, :update, :index, :show]
    resources :question_options,   only: [:new, :create, :edit, :update, :index, :show]
    resources :annotations,        only: [:new, :create, :edit, :update, :index, :show]
    resources :answers,            only: [:new, :create, :edit, :update, :index, :show]
    resources :guidances,          only: [:new, :create, :edit, :update, :index, :show]
    resources :guidance_groups,    only: [:new, :create, :edit, :update, :index, :show]
    resources :themes,             only: [:new, :create, :edit, :update, :index, :show]
    resources :notes,              only: [:new, :create, :edit, :update, :index, :show]
    resources :plans,              only: [:new, :create, :edit, :update, :index, :show]
    resources :identifier_schemes, only: [:new, :create, :edit, :update, :index, :show]
    resources :exported_plans,     only: [:new, :create, :edit, :update, :index, :show]
    resources :regions,            only: [:new, :create, :edit, :update, :index, :show]
    resources :roles,              only: [:new, :create, :edit, :update, :index, :show]
    resources :splash_logs,        only: [:new, :create, :edit, :update, :index, :show]
    resources :user_identifiers,   only: [:new, :create, :edit, :update, :index, :show]
resources :token_permission_types, only: [:new, :create, :edit, :update, :index, :show]
#resources :plans_guidance_groups

    root to: "users#index"
  end

  devise_for :users, controllers: {
        registrations: "registrations",
        passwords: 'passwords',
        sessions: 'sessions',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations' } do

    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

  # WAYFless access point - use query param idp
  #get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  #get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  #post '/auth/:provider/callback' => 'sessions#oauth_create'

  # fix for activeadmin signout bug
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete '/users/identifiers/:id', to: 'user_identifiers#destroy', as: 'destroy_user_identifier'

  get '/orgs/shibboleth', to: 'orgs#shibboleth_ds', as: 'shibboleth_ds'
  get '/orgs/shibboleth/:org_name', to: 'orgs#shibboleth_ds_passthru'
  post '/orgs/shibboleth', to: 'orgs#shibboleth_ds_passthru'
  get '/users/ldap_username', to: 'users#ldap_username'
  post '/users/ldap_account', to: 'users#ldap_account'

  resources :users, path: 'users', only: [] do
    member do
      put 'update_email_preferences'
      put 'org_swap', constraints: {format: [:json]}
    end
  end

  #organisation admin area
  resources :users, :path => 'org/admin/users', only: [] do
    collection do
      get 'admin_index'
    end
    member do
      get 'admin_grant_permissions'
      put 'admin_update_permissions'
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  patch 'locale/:locale' => 'application#set_locale_session', as: 'locale'

  root :to => 'home#index'
    get "about_us" => 'static_pages#about_us'
    get "help" => 'static_pages#help'
    get "roadmap" => 'static_pages#roadmap'
    get "terms" => 'static_pages#termsuse'
    get "public_plans" => 'public_pages#plan_index'
    get "public_templates" => 'public_pages#template_index'
    get "template_export/:id" => 'public_pages#template_export', as: 'template_export'
    get "plan_export/:id" => 'public_pages#plan_export', as: 'plan_export'
    get "existing_users" => 'existing_users#index'
    
    # DMPTool specific documentation pages
    get "get_started" => 'public_pages#get_started', as: 'get_started'
    get "promote" => 'static_pages#promote'
    get "researchers" => 'static_pages#researchers'
    get "faq" => 'static_pages#faq'
    get "general_guidance" => 'static_pages#general_guidance'
    get "quick_start_guide" => 'static_pages#help'
    get "news_media" => 'static_pages#news_media'
    get "public_orgs" => 'public_pages#orgs'

    #post 'contact_form' => 'contacts', as: 'localized_contact_creation'
    #get 'contact_form' => 'contacts#new', as: 'localized_contact_form'

    resources :orgs, :path => 'org/admin', only: [] do
      member do
        get 'children'
        get 'templates'
        get 'admin_show'
        get 'admin_edit'
        put 'admin_update'
      end

      get 'logo', constraints: {format: :json}
    end

    resources :guidances, :path => 'org/admin/guidance', only: [] do
      member do
        get 'admin_show'
        get 'admin_index'
        get 'admin_edit'
        get 'admin_new'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_publish'
        put 'admin_unpublish'
        get 'update_phases'
        get 'update_versions'
        get 'update_sections'
        get 'update_questions'
      end
    end

    resources :guidance_groups, :path => 'org/admin/guidancegroup', only: [] do
      member do
        get 'admin_show'
        get 'admin_new'
        get 'admin_edit'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_update_publish'
        put 'admin_update_unpublish'
      end
    end

    resources :phases, path: 'org/admin/templates/phases', only: [] do
      member do
        get 'admin_show'
        get 'admin_preview'
        get 'admin_add'
        put 'admin_update'
        post 'admin_create'
        delete 'admin_destroy'
      end
    end

    resources :sections, path: 'org/admin/templates/sections', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :questions, path: 'org/admin/templates/questions', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :annotations, path: 'org/admin/templates/annotations', only: [] do
      member do
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :answers, only: [] do
      post 'create_or_update', on: :collection
    end

    # Question Formats controller, currently just the one action
    get 'question_formats/rda_api_address' => 'question_formats#rda_api_address'

    resources :notes, only: [:create, :update, :archive] do
      member do
        patch 'archive'
      end
    end

    resources :plans do
      resources :phases do
        member do
          get 'edit'
          get 'status'
          post 'update'
        end
      end


      member do
        get 'status'
        get 'locked'
        get 'answer'
        put 'update_guidance_choices'
        post 'delete_recent_locks'
        post 'lock_section', constraints: {format: [:html, :json]}
        post 'unlock_section', constraints: {format: [:html, :json]}
        post 'unlock_all_sections'
        get 'warning'
        get 'section_answers'
        get 'share'
        get 'download'
        post 'duplicate'
        get 'export'
        post 'invite'
        post 'visibility', constraints: {format: [:json]}
        post 'set_test', constraints: {format: [:json]}
        get 'request_feedback'
        get 'overview'
      end

      collection do
        get 'possible_templates'
        get 'possible_guidance'
      end
    end

    resources :usage, only: [:index]

    resources :roles, only: [:create, :update, :destroy] do
      member do
        put :deactivate
      end
    end

    namespace :settings do
      resources :plans, only: [:update]
    end

    resources :token_permission_types, only: [:index]

    namespace :api, defaults: {format: :json} do
      namespace :v0 do
        resources :guidances, only: [:index], controller: 'guidance_groups', path: 'guidances'
        resources :plans, only: :create
        resources :templates, only: :index
        resource  :statistics, only: [], controller: "statistics", path: "statistics" do
          member do
            get :users_joined
            get :completed_plans
            get :created_plans
            get :using_template
            get :plans_by_template
            get :plans
          end
        end
      end
    end

    namespace :paginable do
      resources :orgs, only: [] do
        get 'public/:page', action: :public, on: :collection, as: :public
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for plans
      resources :plans, only: [] do
        get 'privately_visible/:page', action: :privately_visible, on: :collection, as: :privately_visible
        get 'organisationally_or_publicly_visible/:page', action: :organisationally_or_publicly_visible, on: :collection, as: :organisationally_or_publicly_visible
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get 'org_admin/:page', action: :org_admin, on: :collection, as: :org_admin
      end
      # Paginable actions for users

app/models/note.rb
class Note < ActiveRecord::Base
  ##
  # Associations
  belongs_to :answer
  belongs_to :user

  ##
  # Possibly needed for active_admin
  #   -relies on protected_attributes gem as syntax depricated in rails 4.2
  attr_accessible :text, :user_id, :answer_id, :archived, :archived_by, 
                  :answer, :user, :as => [:default, :admin]
                  
  validates :text, :answer, :user, presence: {message: _("can't be blank")}
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Note.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Note.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include ConditionalUserMailer
  require "pp"
  after_action :verify_authorized
  respond_to :html

  def create
    @note = Note.new
    @note.user_id = params[:note][:user_id]

    # create answer if we don't have one already
    @answer = nil # if defined within the transaction block, was not accessable afterward
    # ensure user has access to plan BEFORE creating/finding answer
    raise Pundit::NotAuthorizedError unless Plan.find(params[:note][:plan_id]).readable_by?(@note.user_id)
    Answer.transaction do
      @answer = Answer.find_by(plan_id: params[:note][:plan_id], question_id: params[:note][:question_id])
      if @answer.blank?
        @answer = Answer.new
        @answer.plan_id = params[:note][:plan_id]
        @answer.question_id = params[:note][:question_id]
        @answer.user_id = @note.user_id
        @answer.save!
      end
    end

    @note.answer = @answer
    @note.text = params[:note][:text]

    authorize @note

    @plan = @answer.plan

    @question = Question.find(params[:note][:question_id])

    if @note.save
      @status = true
      answer = @note.answer
      plan = answer.plan
      owner = plan.owner
      deliver_if(recipients: owner, key: 'users.new_comment') do |r|
        UserMailer.new_comment(current_user, plan).deliver_now()
      end
      @notice = success_message(_('comment'), _('created'))
      render(json: {
        "notes" => {
          "id" => params[:note][:question_id],
          "html" => render_to_string(partial: 'layout', locals: {plan: @plan, question: @question, answer: @answer }, formats: [:html])
        },
        "title" => {
          "id" => params[:note][:question_id],
          "html" => render_to_string(partial: 'title', locals: { answer: @answer}, formats: [:html])
        }
      }.to_json, status: :created)
    else
      @status = false
      @notice = failed_create_error(@note, _('note'))
      render json: {
        "msg" => @notice
      }.to_json, status: :bad_request
    end
  end

  def update
    @note = Note.find(params[:id])
    authorize @note
    @note.text = params[:note][:text]

    @answer = @note.answer
    @question = @answer.question
    @plan = @answer.plan

    question_id = @note.answer.question_id.to_s

    if @note.update_attributes(params[:note])
      @notice = success_message(_('comment'), _('saved'))
      render(json: {
        "notes" => {
          "id" => question_id,
          "html" => render_to_string(partial: 'layout', locals: {plan: @plan, question: @question, answer: @answer }, formats: [:html])
        },
        "title" => {
          "id" => question_id,
          "html" => render_to_string(partial: 'title', locals: { answer: @answer}, formats: [:html])
        }
      }.to_json, status: :ok)
    else
      @notice = failed_update_error(@note, _('note'))
      render json: {
        "msg" => @notice
      }.to_json, status: :bad_request
    end
  end

  def archive
    @note = Note.find(params[:id])
    authorize @note
    @note.archived = true
    @note.archived_by = params[:note][:archived_by]

    @answer = @note.answer
    @question = @answer.question
    @plan = @answer.plan

    question_id = @note.answer.question_id.to_s

    if @note.update_attributes(params[:note])
      @notice = success_message(_('comment'), _('removed'))
      render(json: {
        "notes" => {
          "id" => question_id,
          "html" => render_to_string(partial: 'layout', locals: {plan: @plan, question: @question, answer: @answer }, formats: [:html])
        },
        "title" => {
          "id" => question_id,
          "html" => render_to_string(partial: 'title', locals: { answer: @answer}, formats: [:html])
        }
      }.to_json, status: :ok)
    else
      @notice = failed_destroy_error(@note, _('note'))
      render json: {
        "msg" => @notice
      }.to_json, status: :bad_request
    end
  end
end

app/views/notes/_archive.html.erb
<%# locals: { note } %>
<% if !note.nil? %>
  <%= form_for(note, url: archive_note_path(note), method: :patch, html: { class: 'archive_note' }) do |f| %>
    <%= f.hidden_field :archived_by, :value => current_user.id %>

    <%= render partial: "notes/show", locals: { note: note }, formats: [:html] %>

    <p><%= _('Are you sure you want to remove this comment?')%></p>
    <div class="pull-right">
      <%= f.button(_('Remove'), class: "btn btn-default", type: "submit") %>
      <%= f.button(_('Cancel'), class: "btn btn-default", type: "button") %>
    </div>
  <% end %>
<% end %>

app/views/notes/_edit.html.erb
<%# locals: { note } %>
<% if !note.nil? %>
    <%= form_for(note, url: note_path(note), method: :put) do |f| %>
        <div class="form-group">
            <%= f.label(:text, _('Edit comment to share with collaborators')) %>
            <%= f.text_area(:text, class: 'form-control', id: "note-#{note.id}") %>
        </div>
        <div class="pull-right">
            <%= f.button(_('Save'), class: "btn btn-default", type: "submit") %>
            <%= f.button(_('Cancel'), class: "btn btn-default", type: "button") %>
        </div>
    <% end %>
<% end %>

app/views/notes/_layout.html.erb
<%# locals: { plan, question, answer } %>
<% notes = answer.non_archived_notes %>
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= render partial: "/notes/list", locals: { question_id: question.id, notes: notes, plan: plan }, formats: [:html] %>  
      </div>
    </div>
    <% if plan.commentable_by?(current_user) %>
      <div class="row">
        <div class="col-md-12">
          <div class="note_new" id="<%= "note_new#{question.id}" %>" data-question-id="<%= question.id %>">
              <%= render partial: "/notes/new", locals: { question: question, answer: answer, plan: plan }, formats: [:html] %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="pull-right">
            <%= link_to(_('Add Comment'), "#note_new#{question.id}", class: "btn btn-default note_new_link", role: "button", style: "visibility: hidden") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/_list.html.erb
<%# locals: { question_id, notes, plan } %>
<% notes.each do |note| %>
    <% if !note.archived %>
        <div class="row">
            <div class="col-md-12">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="pull-left"><!-- note info -->
                            <ul class="list-unstyled">
                                <li><%= note.user.name %></li>
                                <li>(<%= l note.updated_at, format: :short %>)</li>
                            </ul>
                        </div>
                        <div class="pull-right"><!-- note actions -->
                            <ul class="list-inline">
                                <li><%= link_to(_('Show'), "#note_show#{note.id}", class: 'note_show_link') %></li>
                                <% if plan.commentable_by?(current_user) %>
                                  <% if current_user.id == note.user_id %>
                                      <li><%= link_to(_('Edit'), "#note_edit#{note.id}", class: 'note_edit_link') %></li>
                                      <li><%= link_to(_('Remove'), "#note_archive#{note.id}", class: 'note_archive_link') %></li>
                                  <% else  %>
                                      <% if plan.administerable_by?(current_user.id) %>
                                          <li><%= link_to(_('Remove'), "#note_archive#{note.id}", class: 'note_archive_link') %></li>
                                      <% end %>
                                  <% end %>
                                <% end %>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                </ul>
            </div>
        </div>
    <% end %>
<% end %>
<% notes.each do |note| %>
    <% if !note.archived %>
        <div class="row">
          <div class="col-md-12">
            <div class="note_show" id="<%= "note_show#{note.id}" %>" data-question-id="<%= question_id %>" style="display:none;">
                <%= render partial: "/notes/show", locals: { note: note }, formats: [:html] %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="note_edit" id="<%= "note_edit#{note.id}" %>" data-question-id="<%= question_id %>" style="display:none;">
                <%= render partial: "/notes/edit", locals: { note: note }, formats: [:html] %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="note_archive" id="<%= "note_archive#{note.id}" %>" data-question-id="<%= question_id %>" style="display:none;">
                <%= render partial: "/notes/archive", locals: { note: note }, formats: [:html] %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/notes/_new.html.erb
<%# locals: { question, answer, plan } %>
<%= form_for(Note.new, url: notes_path) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :question_id, value: question.id %>
  <%= f.hidden_field :answer_id, value: answer.id %>
  <%= f.hidden_field :plan_id, value: plan.id %>
  <div class="form-group">
    <%= f.label(:text, _('Add comments to share with collaborators')) %>
    <%= f.text_area(:text, class: 'form-control note', id: "note-#{question.id}") %>
  </div>
  <div class="pull-right">
    <%= f.button(_('Save'), class: "btn btn-default", type: "submit") %>
  </div>
<% end %>

app/views/notes/_show.html.erb
<%# locals: { note } %>
<% if !note.nil? %>
    <% user = User.find(note.user_id) %>
    <ul class="list-unstyled">
        <li><%= raw note.text %></li>
        <li>
            <span class="label label-info">
                <%= "#{user.name} at #{l(note.updated_at, format: :short)}" %>
            </span>
        </li>
    </ul>
<% end %>

app/views/notes/_title.html.erb
<%# locals: { answer } %>
<% notes = answer.non_archived_notes %>
<%= _('Comments') %><%= notes.length > 0 ? " (#{notes.length})" : '' %>