config/routes.rb
    resources :guidance_groups,    only: [:new, :create, :edit, :update, :index, :show]
    resources :themes,             only: [:new, :create, :edit, :update, :index, :show]
    resources :notes,              only: [:new, :create, :edit, :update, :index, :show]
    resources :plans,              only: [:new, :create, :edit, :update, :index, :show]
    resources :identifier_schemes, only: [:new, :create, :edit, :update, :index, :show]
    resources :exported_plans,     only: [:new, :create, :edit, :update, :index, :show]
    resources :regions,            only: [:new, :create, :edit, :update, :index, :show]
    resources :roles,              only: [:new, :create, :edit, :update, :index, :show]
    resources :splash_logs,        only: [:new, :create, :edit, :update, :index, :show]
    resources :user_identifiers,   only: [:new, :create, :edit, :update, :index, :show]
resources :token_permission_types, only: [:new, :create, :edit, :update, :index, :show]
#resources :plans_guidance_groups

    root to: "users#index"
  end

  devise_for :users, controllers: {
        registrations: "registrations",
        passwords: 'passwords',
        sessions: 'sessions',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations' } do

    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

  # WAYFless access point - use query param idp
  #get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  #get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  #post '/auth/:provider/callback' => 'sessions#oauth_create'

  # fix for activeadmin signout bug
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete '/users/identifiers/:id', to: 'user_identifiers#destroy', as: 'destroy_user_identifier'

  get '/orgs/shibboleth', to: 'orgs#shibboleth_ds', as: 'shibboleth_ds'
  get '/orgs/shibboleth/:org_name', to: 'orgs#shibboleth_ds_passthru'
  post '/orgs/shibboleth', to: 'orgs#shibboleth_ds_passthru'
  get '/users/ldap_username', to: 'users#ldap_username'
  post '/users/ldap_account', to: 'users#ldap_account'

  resources :users, path: 'users', only: [] do
    member do
      put 'update_email_preferences'
      put 'org_swap', constraints: {format: [:json]}
    end
  end

  #organisation admin area
  resources :users, :path => 'org/admin/users', only: [] do
    collection do
      get 'admin_index'
    end
    member do
      get 'admin_grant_permissions'
      put 'admin_update_permissions'
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  patch 'locale/:locale' => 'application#set_locale_session', as: 'locale'

  root :to => 'home#index'
    get "about_us" => 'static_pages#about_us'
    get "help" => 'static_pages#help'
    get "roadmap" => 'static_pages#roadmap'
    get "terms" => 'static_pages#termsuse'
    get "public_plans" => 'public_pages#plan_index'
    get "public_templates" => 'public_pages#template_index'
    get "template_export/:id" => 'public_pages#template_export', as: 'template_export'
    get "plan_export/:id" => 'public_pages#plan_export', as: 'plan_export'
    get "existing_users" => 'existing_users#index'
    
    # DMPTool specific documentation pages
    get "get_started" => 'public_pages#get_started', as: 'get_started'
    get "promote" => 'static_pages#promote'
    get "researchers" => 'static_pages#researchers'
    get "faq" => 'static_pages#faq'
    get "general_guidance" => 'static_pages#general_guidance'
    get "quick_start_guide" => 'static_pages#help'
    get "news_media" => 'static_pages#news_media'
    get "public_orgs" => 'public_pages#orgs'

    #post 'contact_form' => 'contacts', as: 'localized_contact_creation'
    #get 'contact_form' => 'contacts#new', as: 'localized_contact_form'

    resources :orgs, :path => 'org/admin', only: [] do
      member do
        get 'children'
        get 'templates'
        get 'admin_show'
        get 'admin_edit'
        put 'admin_update'
      end

      get 'logo', constraints: {format: :json}
    end

    resources :guidances, :path => 'org/admin/guidance', only: [] do
      member do
        get 'admin_show'
        get 'admin_index'
        get 'admin_edit'
        get 'admin_new'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_publish'
        put 'admin_unpublish'
        get 'update_phases'
        get 'update_versions'
        get 'update_sections'
        get 'update_questions'
      end
    end

    resources :guidance_groups, :path => 'org/admin/guidancegroup', only: [] do
      member do
        get 'admin_show'
        get 'admin_new'
        get 'admin_edit'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_update_publish'
        put 'admin_update_unpublish'
      end
    end

    resources :phases, path: 'org/admin/templates/phases', only: [] do
      member do
        get 'admin_show'
        get 'admin_preview'
        get 'admin_add'
        put 'admin_update'
        post 'admin_create'
        delete 'admin_destroy'
      end
    end

    resources :sections, path: 'org/admin/templates/sections', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :questions, path: 'org/admin/templates/questions', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :annotations, path: 'org/admin/templates/annotations', only: [] do
      member do
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :answers, only: [] do
      post 'create_or_update', on: :collection
    end

    # Question Formats controller, currently just the one action
    get 'question_formats/rda_api_address' => 'question_formats#rda_api_address'

    resources :notes, only: [:create, :update, :archive] do
      member do
        patch 'archive'
      end
    end

    resources :plans do
      resources :phases do
        member do
          get 'edit'
          get 'status'
          post 'update'
        end
      end


      member do
        get 'status'
        get 'locked'
        get 'answer'
        put 'update_guidance_choices'
        post 'delete_recent_locks'
        post 'lock_section', constraints: {format: [:html, :json]}
        post 'unlock_section', constraints: {format: [:html, :json]}
        post 'unlock_all_sections'
        get 'warning'
        get 'section_answers'
        get 'share'
        get 'download'
        post 'duplicate'
        get 'export'
        post 'invite'
        post 'visibility', constraints: {format: [:json]}
        post 'set_test', constraints: {format: [:json]}
        get 'request_feedback'
        get 'overview'
      end

      collection do
        get 'possible_templates'
        get 'possible_guidance'
      end
    end

    resources :usage, only: [:index]

    resources :roles, only: [:create, :update, :destroy] do
      member do
        put :deactivate
      end
    end

    namespace :settings do
      resources :plans, only: [:update]
    end

    resources :token_permission_types, only: [:index]

    namespace :api, defaults: {format: :json} do
      namespace :v0 do
        resources :guidances, only: [:index], controller: 'guidance_groups', path: 'guidances'
        resources :plans, only: :create
        resources :templates, only: :index
        resource  :statistics, only: [], controller: "statistics", path: "statistics" do
          member do
            get :users_joined
            get :completed_plans
            get :created_plans
            get :using_template
            get :plans_by_template
            get :plans
          end
        end
      end
    end

    namespace :paginable do
      resources :orgs, only: [] do
        get 'public/:page', action: :public, on: :collection, as: :public
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for plans
      resources :plans, only: [] do
        get 'privately_visible/:page', action: :privately_visible, on: :collection, as: :privately_visible
        get 'organisationally_or_publicly_visible/:page', action: :organisationally_or_publicly_visible, on: :collection, as: :organisationally_or_publicly_visible
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get 'org_admin/:page', action: :org_admin, on: :collection, as: :org_admin
      end
      # Paginable actions for users
      resources :users, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for themes
      resources :themes, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for templates
      resources :templates, only: [] do
        get 'all/:page', action: :all, on: :collection, as: :all
        get 'funders/:page', action: :funders, on: :collection, as: :funders
        get 'orgs/:page', action: :orgs, on: :collection, as: :orgs
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get ':id/history/:page', action: :history, on: :collection, as: :history
      end
      # Paginable actions for guidances
      resources :guidances, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for guidance_groups
      resources :guidance_groups, only: [] do
        get 'index/:page', action: :index, on: :collection, as: :index
      end
    end

    # ORG ADMIN specific pages
    namespace :org_admin do

app/views/shared/dmptool/_get_started.html.erb
<div class="row" id="get-started-page">
  <div class="col-md-12 text-center">
    <div id="signin-options-get-started">
      <h2><%= _('Sign in options') %></h2>
      <br>
      <div class="form-group">
        <% step_counter = 1 %>
        <% if Rails.application.config.shibboleth_enabled %>
          <!-- Shibboleth DS enabled -->
          <% if request.fullpath != "/users/sign_up?nosplash=true" && session[:shibboleth_data].nil? then%>
            <h3><%= _('Option %{number}: If your institution is affiliated with DMPTool.') % { number: step_counter } %></h3>
            <% step_counter += 1 %>
            <% if Rails.application.config.shibboleth_use_filtered_discovery_service %>
              <%= link_to _('Your institution'), '#', class: 'btn btn-default btn-block',
                          'data-toggle': 'modal', 'data-target': '#shib-ds-form' %>
            <% else %>
              <%= link_to _('Your institution'), user_shibboleth_omniauth_authorize_path, class: 'btn btn-default btn-block' %>
            <% end %>
            <p><strong><%= _('- or - ') %></strong></p>
          <%else%>
            <%= f.hidden_field :shibboleth_id, :value => session[:shibboleth_data][:uid] %>
          <%end%>
        <% end %>

        <h3><%= _('Option %{number}: If your institution is not affiliated with DMPTool.') % { number: step_counter } %></h3>
        <% step_counter += 1 %>
        <%= link_to _('Email address'), '#', class: 'btn btn-default btn-block', id: 'show-sign-in-form',
                    'data-toggle': 'modal', 'data-target': '#sign-in-create-account' %>
        <p><strong><%= _('- or -') %></strong></p>
        <h3><%= _('Option %{number}: If not affiliated and you need an account.') % { number: step_counter } %></h3>
        <div class="text-center">
          <%= link_to _('Create account with email address'), '#', id: 'show-create-account-form', class: 'btn btn-default btn-block',
                      'data-toggle': 'modal', 'data-target': '#sign-in-create-account' %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Referenced modals are located on the main layouts/application file -->

app/views/shared/dmptool/_my_org.html.erb
<% org_admin = current_user.present? && (current_user.can_org_admin? && !current_user.can_super_admin?) %>
<% tooltip = _('Select an organisation from the list or leave blank if your organisation is not listed.') %>
<% tooltip += _(' Warning: Changing your organisation will result in the loss of your administrative privileges.') if org_admin %>

<%= f.label :org_name, _('Organisation'), class: 'control-label' %>
<%= render partial: 'shared/popover', 
           locals: { message: tooltip, placement: 'right' }%>
<%= render partial: "shared/accessible_combobox",
             locals: {name: "user[org_name]",
                      id: "user_org_name",
                      default_selection: default_org,
                      models: orgs,
                      attribute: 'name'} %>

app/views/shared/dmptool/_org_branding.html.erb
<% if org.present? %>
  <% if org.logo.present? %>
    <%= image_tag(org.logo.thumb('100x100%').url,
                  alt: org.name,
                  class: "org-logo",
                  title: org.name) %>
  <% else %>
    <h4><%= org.name %></h4>
  <% end %>
<% end %>

app/views/shared/dmptool/_shib_ds_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close pull-right" data-dismiss="modal" aria-label="<%= _('Cancel') %>">
        <span class="fa fa-times" aria-hidden="true">&nbsp;</span>
      </button>

      <div class="row">
        <div class="col-md-11">
          <%= label_tag :org_name, _('Look up your institution here'), class: "control-label" %>
          <div class="form-group">
            <% if orgs.length <= 10 %>
              <select id="org_name">
                <option value=""><%= _('Please select one') %></option>
                <%= raw orgs.collect{|o| "<option value=\"#{o.id}\">#{o.name}</option>" }.join('') %>
              </select>
      
            <% else %>
              <%= render partial: "shared/accessible_combobox", 
                         locals: {name: 'org_name',
                                  id: 'org_name',
                                  default_selection: nil,
                                  models: orgs,
                                  attribute: 'name',
                                  required: true,
                                  classes: ''} %>
            <% end %>
            <%= button_tag _('Go'), class: "btn btn-default", id: "org-select-go" %>
          </div>

          <% if orgs.length > 10 %>
            <%= link_to _('See the full list of participating institutions'), '#', id: 'show_list' %>

            <ul id="full_list" class="hide list-unstyled" aria-hidden="true">
              <% current = nil %>
              <% orgs.each do |org| %>
                <% unless org.name[0].capitalize == current %>
                  <% current = org.name[0].capitalize %>
                  <li class="bg-primary"><%= current %></li>
                <% end %>
                <% if org.shibbolized? %>
                  <li><%= link_to org.name, "#{shibboleth_ds_path}/#{org.id}",
                                  'data-content': org.id %></li>
                <% else %>
                  <li>
                    <%= link_to org.name, "#{org_logo_path(org)}", 
                                class: 'org-sign-in', 'data-content': org.id, 
                                'data-toggle': 'modal', 'data-target': '#org-sign-in' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>

          <p>
            <%= _('Institution not in the list?') %>
            <%= link_to _('Create an account with any email address'), '#', 'data-toggle': 'modal',
                        'data-target': '#sign-in-create-account', id: 'show-create-account-via-shib-ds' %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="org-sign-in" class="modal fade" tabindex="-1" role="dialog">
</div>

app/views/shared/dmptool/_sign_in_options.html.erb
<div>
  <h2 class="text-center"><%= _('Sign in options') %></h2>

  <div class="form-group">
    <% step_counter = 1 %>
    <% if Rails.application.config.shibboleth_enabled %>
      <!-- Shibboleth DS enabled -->
      <% if request.fullpath != "/users/sign_up?nosplash=true" && session[:shibboleth_data].nil? then%>
        <h3><%= _('Option %{number}: If your institution is affiliated with DMPTool.') % { number: step_counter } %></h3>
        <% step_counter += 1 %>
        <% if Rails.application.config.shibboleth_use_filtered_discovery_service %>
          <%= link_to _('Your institution'), '#', class: 'btn btn-default btn-block',
                      'data-toggle': 'modal', 'data-target': '#shib-ds-form' %>
        <% else %>
          <%= link_to _('Your institution'), user_shibboleth_omniauth_authorize_path, class: 'btn btn-default btn-block' %>
        <% end %>
        <p><strong><%= _('- or - ') %></strong></p>
      <%else%>
        <%= f.hidden_field :shibboleth_id, :value => session[:shibboleth_data][:uid] %>
      <%end%>
    <% end %>

    <h3><%= _('Option %{number}: If your institution is not affiliated with DMPTool.') % { number: step_counter } %></h3>
    <% step_counter += 1 %>
    <%= link_to _('Email address'), '#', class: 'btn btn-default btn-block', id: 'show-sign-in-form',
                'data-toggle': 'modal', 'data-target': '#sign-in-create-account' %>
    <p><strong><%= _('- or -') %></strong></p>
    <h3><%= _('Option %{number}: If not affiliated and you need an account.') % { number: step_counter } %></h3>
    <div class="text-center">
      <%= link_to _('Create account with email address'), '#', id: 'show-create-account-form', class: 'btn btn-default btn-block',
                  'data-toggle': 'modal', 'data-target': '#sign-in-create-account' %>
    </div>
  </div>
</div>

<!-- Referenced modals are located on the main layouts/application file -->

app/views/shared/dmptool/_signin_create_form.html.erb
<% signin = true unless signin %>
<% url = registration_path("user") unless url %>
<% org = '' unless org %>

<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-body">
      <button type="button" class="close pull-right" data-dismiss="modal" aria-label="<%= _('Cancel') %>">
        <span class="fa fa-times" aria-hidden="true">&nbsp;</span>
      </button>

      <div id="org-sign-in-logo">
      </div>

      <ul id="access-control-tabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <a data-target="#sign-in-form-tab" role="tab" aria-controls="sign-in-form" data-toggle="tab" 
             data-action="<%= user_session_path %>" data-method="POST">
            <%= _('Sign in') %>
          </a>
        </li>
        <li role="presentation">
          <a data-target="#create-account-form-tab" role="tab" aria-controls="create-account-form" data-toggle="tab" 
             data-action="<%= registration_path('user') %>" data-method="POST">
            <%= _('Create account') %>
          </a>
        </li>
      </ul>

      <div class="tab-content">
        <div id="signin-create-content" role="tabpanel" class="tab-pane active">
          <%= form_for resource, as: 'user', url: url, 
                     html: {autocomplete: "off", id: "signin_create_form"} do |f| %>
            <div class="row create-account-fields<%= signin ? ' hide' : '' %>">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label(:firstname, _('First Name'), class: "control-label") %>
                  <%= f.text_field(:firstname, class: "form-control", "aria-required": true) %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label(:surname, _('Last Name'), class: "control-label") %>
                  <%= f.text_field(:surname, class: "form-control", "aria-required": true) %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= f.label(:email, _('Email'), class: "control-label") %>
                  <%= f.email_field(:email, class: "form-control", "aria-required": true, 'data-validatable': true) %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= f.label(:password, _('Password'), class: "control-label") %>
                  <%= f.password_field(:password, class: "form-control", "aria-required": true, 'data-validatable': true) %>
                </div>
              </div>
            </div>

            <div class="row signin-fields<%= !signin ? ' hide' : '' %>">
              <div class="col-md-12">
                <div class="checkbox">
                  <%= label_tag 'remember_email', raw("#{check_box_tag 'remember_email'}#{_('Remember email')}") %>
                </div>
              </div>
            </div>
            <div class="row create-account-fields<%= signin ? ' hide' : '' %>">
              <div class="col-md-12">
                <div class="checkbox pull-left password-toggle">
                  <label for="passwords_toggle_sign_up">
                    <input type="checkbox" id="passwords_toggle_sign_up" class="passwords_toggle" /><%= _('Show password') %>
                  </label>
                </div>
              </div>
              <div class="col-md-12">
                <div class="checkbox pull-left">
                  <%= f.label(:accept_terms,
                      raw("#{ f.check_box(:accept_terms, "aria-required": true, "data-validation-error": _('You must agree to the term and conditions.')) } #{_('I accept the')} <a href=\"#{terms_path}\">#{_('terms and conditions')}</a>")) %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <input type="hidden" value="<%= org.present? ? org.id : '' %>" id="user_org_id" name="user[org_id]" />
                <button type="submit" class="btn btn-default" value=""></button>
              </div>
              <div class="col-md-6 signin-fields<%= !signin ? ' hide' : '' %>">
                <div class="pull-right"><%= link_to _('Forgot email?'), users_ldap_username_path %></div>
                <div class="clearfix"></div>
                <div class="pull-right"><%= link_to _('Forgot password?'), new_password_path('user') %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>