config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users,              only: [:new, :create, :edit, :update, :index, :show]
    resources :orgs,               only: [:new, :create, :edit, :update, :index, :show]
    resources :perms,              only: [:new, :create, :edit, :update, :index, :show]
    resources :languages,          only: [:new, :create, :edit, :update, :index, :show]
    resources :templates,          only: [:new, :create, :edit, :update, :index, :show]
    resources :phases,             only: [:new, :create, :edit, :update, :index, :show]
    resources :sections,           only: [:new, :create, :edit, :update, :index, :show]
    resources :questions,          only: [:new, :create, :edit, :update, :index, :show]
    resources :question_formats,   only: [:new, :create, :edit, :update, :index, :show]
    resources :question_options,   only: [:new, :create, :edit, :update, :index, :show]
    resources :annotations,        only: [:new, :create, :edit, :update, :index, :show]
    resources :answers,            only: [:new, :create, :edit, :update, :index, :show]
    resources :guidances,          only: [:new, :create, :edit, :update, :index, :show]
    resources :guidance_groups,    only: [:new, :create, :edit, :update, :index, :show]
    resources :themes,             only: [:new, :create, :edit, :update, :index, :show]
    resources :notes,              only: [:new, :create, :edit, :update, :index, :show]
    resources :plans,              only: [:new, :create, :edit, :update, :index, :show]
    resources :identifier_schemes, only: [:new, :create, :edit, :update, :index, :show]
    resources :exported_plans,     only: [:new, :create, :edit, :update, :index, :show]
    resources :regions,            only: [:new, :create, :edit, :update, :index, :show]
    resources :roles,              only: [:new, :create, :edit, :update, :index, :show]
    resources :splash_logs,        only: [:new, :create, :edit, :update, :index, :show]
    resources :user_identifiers,   only: [:new, :create, :edit, :update, :index, :show]
resources :token_permission_types, only: [:new, :create, :edit, :update, :index, :show]
#resources :plans_guidance_groups

    root to: "users#index"
  end

  devise_for :users, controllers: {
        registrations: "registrations",
        passwords: 'passwords',
        sessions: 'sessions',
        omniauth_callbacks: 'users/omniauth_callbacks',
        invitations: 'users/invitations' } do

    get "/users/sign_out", :to => "devise/sessions#destroy"
  end

  # WAYFless access point - use query param idp
  #get 'auth/shibboleth' => 'users/omniauth_shibboleth_request#redirect', :as => 'user_omniauth_shibboleth'
  #get 'auth/shibboleth/assoc' => 'users/omniauth_shibboleth_request#associate', :as => 'user_shibboleth_assoc'
  #post '/auth/:provider/callback' => 'sessions#oauth_create'

  # fix for activeadmin signout bug
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  delete '/users/identifiers/:id', to: 'user_identifiers#destroy', as: 'destroy_user_identifier'

  get '/orgs/shibboleth', to: 'orgs#shibboleth_ds', as: 'shibboleth_ds'
  get '/orgs/shibboleth/:org_name', to: 'orgs#shibboleth_ds_passthru'
  post '/orgs/shibboleth', to: 'orgs#shibboleth_ds_passthru'
  get '/users/ldap_username', to: 'users#ldap_username'
  post '/users/ldap_account', to: 'users#ldap_account'

  resources :users, path: 'users', only: [] do
    member do
      put 'update_email_preferences'
      put 'org_swap', constraints: {format: [:json]}
    end
  end

  #organisation admin area
  resources :users, :path => 'org/admin/users', only: [] do
    collection do
      get 'admin_index'
    end
    member do
      get 'admin_grant_permissions'
      put 'admin_update_permissions'
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.

  patch 'locale/:locale' => 'application#set_locale_session', as: 'locale'

  root :to => 'home#index'
    get "about_us" => 'static_pages#about_us'
    get "help" => 'static_pages#help'
    get "roadmap" => 'static_pages#roadmap'
    get "terms" => 'static_pages#termsuse'
    get "public_plans" => 'public_pages#plan_index'
    get "public_templates" => 'public_pages#template_index'
    get "template_export/:id" => 'public_pages#template_export', as: 'template_export'
    get "plan_export/:id" => 'public_pages#plan_export', as: 'plan_export'
    get "existing_users" => 'existing_users#index'
    
    # DMPTool specific documentation pages
    get "get_started" => 'public_pages#get_started', as: 'get_started'
    get "promote" => 'static_pages#promote'
    get "researchers" => 'static_pages#researchers'
    get "faq" => 'static_pages#faq'
    get "general_guidance" => 'static_pages#general_guidance'
    get "quick_start_guide" => 'static_pages#help'
    get "news_media" => 'static_pages#news_media'
    get "public_orgs" => 'public_pages#orgs'

    #post 'contact_form' => 'contacts', as: 'localized_contact_creation'
    #get 'contact_form' => 'contacts#new', as: 'localized_contact_form'

    resources :orgs, :path => 'org/admin', only: [] do
      member do
        get 'children'
        get 'templates'
        get 'admin_show'
        get 'admin_edit'
        put 'admin_update'
      end

      get 'logo', constraints: {format: :json}
    end

    resources :guidances, :path => 'org/admin/guidance', only: [] do
      member do
        get 'admin_show'
        get 'admin_index'
        get 'admin_edit'
        get 'admin_new'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_publish'
        put 'admin_unpublish'
        get 'update_phases'
        get 'update_versions'
        get 'update_sections'
        get 'update_questions'
      end
    end

    resources :guidance_groups, :path => 'org/admin/guidancegroup', only: [] do
      member do
        get 'admin_show'
        get 'admin_new'
        get 'admin_edit'
        delete 'admin_destroy'
        post 'admin_create'
        put 'admin_update'
        put 'admin_update_publish'
        put 'admin_update_unpublish'
      end
    end

    resources :phases, path: 'org/admin/templates/phases', only: [] do
      member do
        get 'admin_show'
        get 'admin_preview'
        get 'admin_add'
        put 'admin_update'
        post 'admin_create'
        delete 'admin_destroy'
      end
    end

    resources :sections, path: 'org/admin/templates/sections', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :questions, path: 'org/admin/templates/questions', only: [] do
      member do
        post 'admin_create'
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :annotations, path: 'org/admin/templates/annotations', only: [] do
      member do
        put 'admin_update'
        delete 'admin_destroy'
      end
    end

    resources :answers, only: [] do
      post 'create_or_update', on: :collection
    end

    # Question Formats controller, currently just the one action
    get 'question_formats/rda_api_address' => 'question_formats#rda_api_address'

    resources :notes, only: [:create, :update, :archive] do
      member do
        patch 'archive'
      end
    end

    resources :plans do
      resources :phases do
        member do
          get 'edit'
          get 'status'
          post 'update'
        end
      end


      member do
        get 'status'
        get 'locked'
        get 'answer'
        put 'update_guidance_choices'
        post 'delete_recent_locks'
        post 'lock_section', constraints: {format: [:html, :json]}
        post 'unlock_section', constraints: {format: [:html, :json]}
        post 'unlock_all_sections'
        get 'warning'
        get 'section_answers'
        get 'share'
        get 'download'
        post 'duplicate'
        get 'export'
        post 'invite'
        post 'visibility', constraints: {format: [:json]}
        post 'set_test', constraints: {format: [:json]}
        get 'request_feedback'
        get 'overview'
      end

      collection do
        get 'possible_templates'
        get 'possible_guidance'
      end
    end

    resources :usage, only: [:index]

    resources :roles, only: [:create, :update, :destroy] do
      member do
        put :deactivate
      end
    end

    namespace :settings do
      resources :plans, only: [:update]
    end

    resources :token_permission_types, only: [:index]

    namespace :api, defaults: {format: :json} do
      namespace :v0 do
        resources :guidances, only: [:index], controller: 'guidance_groups', path: 'guidances'
        resources :plans, only: :create
        resources :templates, only: :index
        resource  :statistics, only: [], controller: "statistics", path: "statistics" do
          member do
            get :users_joined
            get :completed_plans
            get :created_plans
            get :using_template
            get :plans_by_template
            get :plans
          end
        end
      end
    end

    namespace :paginable do
      resources :orgs, only: [] do
        get 'public/:page', action: :public, on: :collection, as: :public
        get 'index/:page', action: :index, on: :collection, as: :index
      end
      # Paginable actions for plans
      resources :plans, only: [] do
        get 'privately_visible/:page', action: :privately_visible, on: :collection, as: :privately_visible
        get 'organisationally_or_publicly_visible/:page', action: :organisationally_or_publicly_visible, on: :collection, as: :organisationally_or_publicly_visible
        get 'publicly_visible/:page', action: :publicly_visible, on: :collection, as: :publicly_visible
        get 'org_admin/:page', action: :org_admin, on: :collection, as: :org_admin
      end
      # Paginable actions for users

app/controllers/admin/plans_controller.rb
module Admin
  class PlansController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Plan.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Plan.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v0/plans_controller.rb
module Api
  module V0
    class PlansController < Api::V0::BaseController
      before_action :authenticate

      ##
      # Creates a new plan based on the information passed in JSON to the API
      def create
        @template = Template.live(params[:template_id])
        raise Pundit::NotAuthorizedError unless Api::V0::PlansPolicy.new(@user, @template).create?

        plan_user = User.find_by(email: params[:plan][:email])
        # ensure user exists
        if plan_user.blank?
          User.invite!({email: params[:plan][:email]}, ( @user))
          plan_user = User.find_by(email: params[:plan][:email])
          plan_user.org = @user.org
          plan_user.save
        end
        # ensure user's organisation is the same as api user's 
        raise Pundit::NotAuthorizedError, _("user must be in your organisation") unless plan_user.org == @user.org

        # initialize the plan
        @plan = Plan.new
        @plan.principal_investigator = plan_user.surname.blank? ? nil : "#{plan_user.firstname} #{plan_user.surname}"
        @plan.data_contact = plan_user.email
        # set funder name to template's org, or original template's org
        if @template.customization_of.nil?
          @plan.funder_name = @template.org.name
        else
          @plan.funder_name = Template.where(dmptemplate_id: @template.customization_of).first.org.name
        end
        @plan.template = @template
        @plan.title = params[:plan][:title]
        if @plan.save
          @plan.assign_creator(plan_user)
          respond_with @plan
        else
          # the plan did not save 
          self.headers['WWW-Authenticate'] = "Token realm=\"\""
          render json: _("Bad Parameters"), status: 400
        end
      end


    end
  end
end

app/controllers/org_admin/plans_controller.rb
module OrgAdmin
  class PlansController < ApplicationController
    # GET org_admin/plans
    def index
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      vals = Role.access_values_for(:reviewer)
      @feedback_plans = Plan.joins(:roles).where('roles.user_id = ? and roles.access IN (?)', current_user.id, vals)
      @plans = current_user.org.plans
    end
    
    # GET org_admin/plans/:id/feedback_complete
    def feedback_complete
      plan = Plan.find(params[:id])
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      raise Pundit::NotAuthorizedError unless plan.reviewable_by?(current_user.id)
      
      if plan.complete_feedback(current_user)
        redirect_to org_admin_plans_path, notice: _('%{plan_owner} has been notified that you have finished providing feedback') % { plan_owner: plan.owner.name(false) }
      else
        redirect_to org_admin_plans_path, alert: _('Unable to notify user that you have finished providing feedback.')
      end
    end
    
    # GET /org_admin/download_plans
    def download_plans
      # Test auth directly and throw Pundit error sincePundit is unaware of namespacing
      raise Pundit::NotAuthorizedError unless current_user.present? && current_user.can_org_admin?
      
      org = current_user.org
      file_name = org.name.gsub(/ /, "_")
      header_cols = [
        "#{_('Project title')}",
        "#{_('Template')}",
        "#{_('Organisation')}",
        "#{_('Owner name')}",
        "#{_('Owner email')}",
        "#{_('Updated')}",
        "#{_('Visibility')}"
      ]
      
      plans = CSV.generate do |csv|
        csv << header_cols
        org.plans.includes(template: :org).order(updated_at: :desc).each do |plan|
          owner = plan.owner
          csv << [
            "#{plan.title}", 
            "#{plan.template.title}", 
            "#{plan.owner.org.present? ? plan.owner.org.name : ''}", 
            "#{plan.owner.name(false)}",
            "#{plan.owner.email}",
            "#{l(plan.latest_update.to_date, formats: :short)}",
            "#{Plan.visibility_message(plan.visibility.to_sym).capitalize}"
          ] 
        end
      end

      respond_to do |format|
        format.csv  { send_data plans,  filename: "#{file_name}.csv" }
      end
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
  # Shows whether the user has default, template-default or custom settings
  # for the given plan.
  # --------------------------------------------------------
  def plan_settings_indicator(plan)
    plan_settings     = plan.super_settings(:export)
    template_settings = plan.template.try(:settings, :export)

    key = if plan_settings.try(:value?)
      plan_settings.formatting == template_settings.formatting ? "template_formatting" : "custom_formatting"
    elsif template_settings.try(:value?)
      "template_formatting"
    else
      "default_formatting"
    end

    content_tag(:small, t("helpers.settings.plans.#{key}"))
  end

  # display the role of the user for a given plan
  def display_role(role)
    if role.creator?
      access = _('Owner')
      
    else
      case role.access_level
        when 3
          access = _('Co-owner')
        when 2
          access = _('Editor')
        when 1
          access = _('Read only')
      end
    end
    return access
  end

  # display the visibility of the plan
  def display_visibility(val)
    case val
    when 'organisationally_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Organisation')}</span>"
    when 'publicly_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Public')}</span>"
    when 'privately_visible'
      return "<span title=\"#{ visibility_tooltip(val) }\">#{_('Private')}</span>"
    else
      return "<span>#{_('Private')}</span>" # Test Plans
    end
  end
  
  def visibility_tooltip(val)
    case val
    when 'organisationally_visible'
      return _('Organisation: anyone at my organisation can view.')
    when 'publicly_visible'
      return _('Public: anyone can view.')
    else
      return _('Private: restricted to me and people I invite.')
    end
  end
end

app/views/plans/_guidance_choices.html.erb
<% choices.each do |org, groups| %>
  <% if groups && groups.size == 1 %>
    <li class="checkbox">
      <%= check_box_tag "guidance_group_ids[]", groups[0].id,
                        current_selections.include?(groups[0].id), class: 'guidance-choice' %>
      <%# DMPTool hack to swap in 'DMPTool' for 'DCC' in guidance selection %>
      <%= (org.abbreviation == 'UCOP' ? _('DMPTool') : org.name) %>
    </li>
  <% elsif groups %>
    <li class="checkbox">
      <%= org.name %>
      <ul>
        <% groups.each do |group| %>
          <li class="checkbox">
            <span class="sublist">└─ </span>
            <%= check_box_tag "guidance_group_ids[]", group.id,
                              current_selections.include?(group.id), class: 'guidance-choice' %>
            <%= group.name %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end%>
<% end %>

app/views/plans/_navigation.html.erb
<% phases = Phase.titles(plan.template.id) %>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="<%= (isActivePage(plan_path(plan), true) ? 'active' : '') %>">
    <a href="<%= plan_path(plan) %>" role="tab" aria-controls="content"><%= _('Project Details') %></a>
  </li>
  <li role="presentation" class="<%= (isActivePage(overview_plan_path(plan)) ? 'active' : '') %>">
    <%= link_to(_('Plan overview'), overview_plan_path(plan), role: 'tab', 'aria-controls': 'content') %>
  </li>
  <% phases.each do |phase| %>
    <li role="presentation" class="<%= (isActivePage(edit_plan_phase_path(plan, phase)) ? 'active' : '') %>">
      <a href="<%= edit_plan_phase_path(plan, phase) %>" role="tab" aria-controls="content">
        <%= (phases.size > 1 ? phase.title : _('Write Plan')) %>
      </a>
    </li>
  <% end %>
  <% if plan.editable_by?(current_user) %>
    <li role="presentation" class="<%= (isActivePage(share_plan_path(plan)) ? 'active' : '') %>">
      <a href="<%= share_plan_path(plan) %>" role="tab" aria-controls="content"><%= _('Share') %></a>
    </li>
  <% end %>
  <li role="presentation" class="<%= (isActivePage(download_plan_path(plan)) ? 'active' : '') %>">
    <a href="<%= download_plan_path(plan) %>" role="tab" aria-controls="content"><%= _('Download') %></a>
  </li>
</ul>
<div class="tab-content">
  <div id="content" role="tabpanel" class="tab-pane active">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/plans/_progress.html.erb
<%# locals: { plan, current_phase } %>
<%
  nanswers = current_phase.num_answered_questions(plan)
  nquestions = current_phase.num_questions()
  value=(nanswers.to_f/nquestions*100).round(2)
%>
<div class="progress-bar" role="progressbar"
  aria-valuenow="<%= value %>"
  aria-valuemin="0" aria-valuemax="100"
  style="min-width: 7em; width: <%= "#{value}%" %>;">
    <%= "#{nanswers}/#{nquestions} #{_('answered')}" %>
</div>

app/views/plans/_share_form.html.erb
<h2><%= _('Set plan visibility') %></h2>
<p class="form-control-static"><%= _('Public or organisational visibility is intended for finished plans. You must answer at least %{percentage}%% of the questions to enable these options. Note: test plans are set to private visibility by default.') % { :percentage => Rails.application.config.default_plan_percentage_answered } %></p>
<% allow_visibility = @plan.visibility_allowed? %>
<%= form_for(@plan, url: visibility_plan_path, method: :post, html: { id: 'set_visibility', remote: true }) do |f| %>
  <fieldset<%= (allow_visibility ? '' : ' disabled') %>>
    <div class="form-group col-xs-8">
      <div class="radio">
        <%= f.label :visibility_privately_visible, raw("#{f.radio_button :visibility, :privately_visible}\
        #{_('Private: visible to me, specified collaborators and administrators at my organisation')}") %>
      </div>
      <div class="radio">
        <%= f.label :visibility_organisationally_visible, raw("#{f.radio_button :visibility, :organisationally_visible} #{_('Organisation: anyone at my organisation can view')}") %>
      </div>
      <div class="radio">
        <%= f.label :visibility_publicly_visible, raw("#{f.radio_button :visibility, :publicly_visible} #{_('Public: anyone can view')}") %>
      </div>
    </div>
    <div class="col-xs-8">
      <%= f.submit(_('Update'), style: 'display:none') %>
    </div>
  </fieldset>
<% end %>

<h2><%= _('Manage collaborators')%></h2>
<p><%= _('Invite specific people to read, edit, or administer your plan. Invitees will receive an email notification that they have access to this plan.') %></p>
<% administerable = @plan.administerable_by?(current_user) %>
<% if @plan.roles.any? then %>
  <table class="table table-hover table-bordered" id="collaborator-table">
    <thead>
      <tr>
        <th><%= _('Email address')%></th>
        <th><%= _('Permissions')%></th>
        <% if administerable %>
          <th><span aria-hidden="false" class="sr-only"><%= _('Actions') %></span></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @plan_roles.each do |role| %>
        <tr>
          <td><%= role.user.name %></td>
          <td>
            <% if role.creator? %>
                <span><%= _('Owner') %></span> 
            <% else %>
                <% if administerable && role.user != current_user %>
                      <%= form_for role, url: { controller: :roles, action: :update, id: role.id }, remote: true, html: { method: :put } do |f| %>
                      <div class="form-group col-xs-8">
                        <%= f.hidden_field :id %>
                        <%= f.select :access_level, {"#{_('Co-owner')}": 3, "#{_('Editor')}": 2, "#{_('Read only')}": 1}, {}, {id: "#{role.id}-can-edit", class: "toggle-existing-user-access" } %>
                      </div>
                    <% end %>
                <% else %>
                    <span><%= display_role(role) %></span>
                <% end %>
            <% end %>
          <% if administerable %>
            <td>
              <% unless role.creator? || role.user == current_user then %>
                <%= link_to _('Remove'), role, method: :delete, data: { confirm: _('Are you sure?') }, :class => "a-orange" %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<h2><%= _('Invite collaborators') %></h2>
<% new_role = Role.new %>
<% new_role.plan = @plan %>
<%= form_for new_role, url: {controller: :roles, action: :create }, html: {method: :post} do |f| %>
  <div class="form-group col-xs-8">
    <%= f.hidden_field :plan_id %>
    <%= f.fields_for :user do |user| %>
      <%= user.label :email, _('Email'), class: 'control-label' %>
      <%= user.email_field :email, for: :user, name: "user", class: "form-control", "aria-required": true %>
    <% end %>
  </div>

  <div class="form-group col-xs-8">
    <p><strong><%= _('Permissions') %></strong></p>
    <div class="radio">
      <%= f.label :access_level, raw("#{f.radio_button :access_level, 3, "aria-required": true} #{_('Co-owner: can edit project details, change visibility, and add collaborators')}") %>
    </div>
    <div class="radio">
      <%= f.label :access_level, raw("#{f.radio_button :access_level, 2} #{_('Editor: can comment and make changes')}") %>
    </div>
    <div class="radio">
      <%= f.label :access_level, raw("#{f.radio_button :access_level, 1} #{_('Read only: can view and comment, but not make changes')}") %>
    </div>

    <%= f.button(_('Send invitation'), class: "btn btn-primary", type: "submit") %>
  </div>
  <div class="clearfix"></div>
<% end %>

<% if plan.owner_and_coowners.include?(current_user) && current_user.org.present? && current_user.org.feedback_enabled? %>
  <h2><%= _('Request expert feedback') %></h2>
  <p><%= _('Click below to give data management staff at your organisation access to read and comment on your plan.') %></p>
  <p><%= _('You can continue to edit and download the plan in the interim.') %></p>

  <div class="form-group col-xs-8">
    <%= link_to _('Request feedback'), request_feedback_plan_path, class: "btn btn-default#{' disabled' if @plan.feedback_requested?}" %>
    <span><%= _("Feedback has been requested.") if @plan.feedback_requested? %></span>
  </div>
<% end %>

app/views/plans/export.erb
<!-- would be better to simply point the controller to this partial instead -->
<%= render partial: '/shared/export/plan', locals: local_assigns %>

app/views/plans/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= _('Create a new plan') %></h1>

    <p class="left-indent">
      <%= _("Before you get started, we need some information about your research project to set you up with the best DMP template for your needs.") %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for Plan.new, url: plans_path do |f| %>
      <!-- Plan name section -->
      <h2 id="project-title"><%= _('What research project are you planning?') %></h2>
      <div class="form-group row">
        <div class="col-xs-6">
          <%= f.text_field(:title, class: 'form-control', 'aria-describedby': 'project-title', 'aria-required': 'true', 
                'data-toggle': 'tooltip',
                title: _('If applying for funding, state the project title exactly as in the proposal.')) %>
        </div>
        <div class="col-md-1">&nbsp;</div>
        <div class="col-xs-5 checkbox create-plan-mock">
          <%= label_tag(:is_test, raw("#{check_box_tag(:is_test, "1", false)} #{_('Mock project for testing, practice, or educational purposes')}")) %>
        </div>
      </div>

      <!-- Organisation selection -->
      <h2 id="research-org"><%= _('Select the primary research organisation') %></h2>
      <div class="form-group row">
        <div class="col-md-6">
          <%= render partial: "shared/accessible_combobox", 
                     locals: {name: 'plan[org_name]',
                              id: 'plan_org_name',
                              default_selection: @default_org,
                              models: @orgs,
                              attribute: 'name',
                              required: true,
                              error: _('You must select a research organisation from the list.'),
                              tooltip: _('Please select a valid research organisation from the list.')} %>
        </div>
        <div class="col-md-1 pad-top-10 create-plan-or"><strong>- <%= _('or') %> -</strong></div>
        <div class="col-md-5 create-plan-checkbox">
          <div class="checkbox">
            <%= label_tag(:plan_no_org, raw("#{check_box_tag(:plan_no_org)} #{_('My research organisation is not on the list')} <em>#{_(' or ')}</em> #{_('no research organisation is associated with this plan')}")) %>
          </div>
        </div>
      </div>
  
      <!-- Funder selection -->
      <h2 id="funder-org"><%= _('Select the primary funding organisation') %></h2>
      <div class="form-group row">
        <div class="col-xs-6">
          <%= render partial: "shared/accessible_combobox", 
                     locals: {name: 'plan[funder_name]',
                              id: 'plan_funder_name',
                              default_selection: nil,
                              models: @funders,
                              attribute: 'name',
                              required: true,
                              error: _('You must select a funding organisation from the list.'),
                              tooltip: _('Please select a valid funding organisation from the list.')} %>
        </div>
        <div class="col-md-1 create-plan-or"><strong>- <%= _('or') %> -</strong></div>
        <div class="col-xs-5 create-plan-checkbox">
          <div class="checkbox">
            <%= label_tag(:plan_no_funder, raw("#{check_box_tag(:plan_no_funder)} #{_('No funder associated with this plan')}")) %>
          </div>
        </div>
      </div>

      <!-- Template selection -->
      <div id="available-templates" style="visibility: none;">
        <%= hidden_field_tag 'template-option-target', org_admin_template_options_path %>
        <h2 id="template-selection"><%= _('Which DMP template would you like to use?') %></h2>
        <div class="form-group row">
          <div class="col-xs-6">
            <%= select_tag(:plan_template_id, "<option value=\"\">#{_('Please select a template')}</option>", name: 'plan[template_id]',
                           class: 'form-control', 'aria-describedby': 'template-selection') %>
          </div>
          <div class="col-xs-6">
            <span id="multiple-templates"><%= _('We found multiple DMP templates corresponding to your funder.') %></span>
          </div>
        </div>
      </div>

      <%= f.hidden_field(:visibility, value: @is_test ? 'is_test' : Rails.application.config.default_plan_visibility) %>
      <%= f.button(_('Create plan'), class: "btn btn-primary", type: "submit") %>
      <%= link_to _('Cancel'), plans_path, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>